apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    name: http
    protocol: TCP
  - name: ampq
    port: 5672
    targetPort: 5672
    protocol: TCP
